CREATE TABLE `finance_dashboard`.`Role_TB`(
RoleID INT NOT NULL AUTO_INCREMENT,
RoleName VARCHAR(50) NOT NULL,
RoleDescription VARCHAR(200),
Status BOOLEAN NOT NULL DEFAULT 0,
CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UpdatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(`RoleID`))